/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.paul.teacher;

import com.paul.admin.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JScrollBar;
import net.proteanit.sql.DbUtils;
import scrollbar.ScrollBarCustom;

/**
 *
 * @author ASUS ROG STRIX
 */
public class viewstudentpanel extends javax.swing.JPanel {

    /**
     * Creates new form addaccountpanel
     */
    public viewstudentpanel() {
        initComponents();
        tableinfo();
      
    }
public void tableinfo(){
    Connection Con = null;
        Statement St = null;
        ResultSet Rs = null;
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/studentportal", "root", "");
            St = Con.createStatement();
            Rs = St.executeQuery("SELECT `student_id` AS 'Student ID', `SR_Code` AS 'SR CODE',`Name` AS Name, `email` as Email, `Sex` AS Sex, `birthday` AS Birthday, `Program`, `Track`, `yearLevel` as 'Year Level', `age`as Age FROM `student`");

            jTable1.setModel(DbUtils.resultSetToTableModel(Rs));

            System.out.println("Connection successfully loaded.");
        } catch (Exception e) {
            e.printStackTrace();
        }
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroll = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        textField4 = new textfield.TextField();

        setBackground(new java.awt.Color(153, 153, 153));
        setAutoscrolls(true);
        setPreferredSize(new java.awt.Dimension(1190, 630));

        scroll.setBackground(new java.awt.Color(0, 0, 0));
        scroll.setVerticalScrollBar(new ScrollBarCustom());
        ScrollBarCustom sp = new ScrollBarCustom();
        sp.setOrientation(JScrollBar.HORIZONTAL);
        scroll.setHorizontalScrollBar(sp);
        scroll.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        scroll.setToolTipText("");

        jTable1.setBackground(java.awt.SystemColor.control);
        jTable1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setEnabled(false);
        jTable1.setGridColor(java.awt.SystemColor.control);
        jTable1.setRowHeight(40);
        scroll.setViewportView(jTable1);

        textField4.setLabelText("SEARCH NAME");
        textField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textField4KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textField4KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(939, 939, 939)
                .addComponent(textField4, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addGap(23, 23, 23))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 1145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(24, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(textField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(565, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(85, 85, 85)
                    .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(32, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField4KeyPressed

    }//GEN-LAST:event_textField4KeyPressed

    private void textField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField4KeyReleased
     
        try {
            Connection Con = null;
            Statement St = null;
            ResultSet Rs = null;

            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/studentportal", "root", "");

            St = Con.createStatement();
            Rs = St.executeQuery("SELECT `student_id` AS 'Student ID', `SR_Code` AS 'SR CODE',`Name` AS Name, `email` as Email, `Sex` AS Sex, `birthday` AS Birthday, `Program`, `Track`, `yearLevel` as 'Year Level', `age`as Age FROM `student` where Name like'%"+textField4.getText()+"%'");

            jTable1.setModel(DbUtils.resultSetToTableModel(Rs));

            Rs.close();
            Con.close();
        } catch (SQLException ex) {
            Logger.getLogger(viewstudentpanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_textField4KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane scroll;
    private textfield.TextField textField4;
    // End of variables declaration//GEN-END:variables
}
