/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.paul.admin;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JScrollBar;
import net.proteanit.sql.DbUtils;
import scrollbar.ScrollBarCustom;

/**
 *
 * @author ASUS ROG STRIX
 */
public class viewaccountpanel extends javax.swing.JPanel {

    /**
     * Creates new form addaccountpanel
     */
    public viewaccountpanel() {
        initComponents();
        tableinfo();
        tableinfo() ;
    }

    public void tableinfo() {
        Connection Con = null;
        Statement St = null;
        ResultSet Rs = null;
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/studentportal", "root", "");
            St = Con.createStatement();
            Rs = St.executeQuery("SELECT user_id as 'User ID', `username` as Username, `role` as Position, `password` as Password FROM users");

            jTable1.setModel(DbUtils.resultSetToTableModel(Rs));

            System.out.println("Connection successfully loaded.");
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroll = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        textField4 = new textfield.TextField();
        combobox1 = new combobox.Combobox();

        setBackground(new java.awt.Color(153, 153, 153));
        setAutoscrolls(true);
        setPreferredSize(new java.awt.Dimension(1190, 630));

        scroll.setBackground(new java.awt.Color(0, 0, 0));
        scroll.setVerticalScrollBar(new ScrollBarCustom());
        ScrollBarCustom sp = new ScrollBarCustom();
        sp.setOrientation(JScrollBar.HORIZONTAL);
        scroll.setHorizontalScrollBar(sp);
        scroll.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        scroll.setToolTipText("");

        jTable1.setBackground(java.awt.SystemColor.control);
        jTable1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setEnabled(false);
        jTable1.setGridColor(java.awt.SystemColor.control);
        jTable1.setRowHeight(40);
        scroll.setViewportView(jTable1);

        textField4.setLabelText("SEARCH USERNAME");
        textField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textField4KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textField4KeyReleased(evt);
            }
        });

        combobox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Admin", "Teacher", "Student" }));
        combobox1.setLabeText("Position");
        combobox1.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                combobox1HierarchyChanged(evt);
            }
        });
        combobox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox1ActionPerformed(evt);
            }
        });
        combobox1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                combobox1PropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(571, 571, 571)
                .addComponent(combobox1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(textField4, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addGap(28, 28, 28))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 1145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(24, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(combobox1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(textField4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(553, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(85, 85, 85)
                    .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(32, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField4KeyPressed

    }//GEN-LAST:event_textField4KeyPressed

    private void textField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField4KeyReleased
        try {
            Connection Con = null;
            Statement St = null;
            ResultSet Rs = null;

            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/studentportal", "root", "");

            St = Con.createStatement();
            Rs = St.executeQuery("SELECT user_id as 'User ID', `username` as Username, `role` as Position, `password` as Password FROM users where Username like'%" + textField4.getText() + "%'");

            jTable1.setModel(DbUtils.resultSetToTableModel(Rs));

            Rs.close();
            Con.close();
        } catch (SQLException ex) {
            Logger.getLogger(viewaccountpanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_textField4KeyReleased

    private void combobox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox1ActionPerformed
  try {
            Connection Con = null;
            Statement St = null;
            ResultSet Rs = null;

            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/studentportal", "root", "");

            St = Con.createStatement();
            Rs = St.executeQuery("SELECT user_id as 'User ID', `username` as Username, `role` as Position, `password` as Password FROM users where role='" + combobox1.getSelectedItem().toString() + "'");

            jTable1.setModel(DbUtils.resultSetToTableModel(Rs));

            Rs.close();
            Con.close();
        } catch (SQLException ex) {
            Logger.getLogger(viewaccountpanel.class.getName()).log(Level.SEVERE, null, ex);
        }    }//GEN-LAST:event_combobox1ActionPerformed

    private void combobox1HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_combobox1HierarchyChanged

    }//GEN-LAST:event_combobox1HierarchyChanged

    private void combobox1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_combobox1PropertyChange
    }//GEN-LAST:event_combobox1PropertyChange
    public void searchstudentcb() {
        try {
            Connection Con = null;
            Statement St = null;
            ResultSet Rs = null;

            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/studentportal", "root", "");

            St = Con.createStatement();
            Rs = St.executeQuery("SELECT user_id as 'User ID', `username` as Username, `role` as Position, `password` as Password FROM users where Username='" + textField4.getText() + "' and role='" + combobox1.getSelectedItem().toString() + "'");

            jTable1.setModel(DbUtils.resultSetToTableModel(Rs));

            Rs.close();
            Con.close();
        } catch (SQLException ex) {
            Logger.getLogger(viewaccountpanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private combobox.Combobox combobox1;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane scroll;
    private textfield.TextField textField4;
    // End of variables declaration//GEN-END:variables
}
